# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zd5SWrA4sxkZiH8mWAQmkiLQhgMkOHUP
"""

import pandas as pd
#Load the dataset
cars_df = pd.read_csv('cars.csv')

print("Q1: Find all Null Values in the dataset. If there is any null value in any column, fill it with the mean of that column. \n")
cars_df.fillna(cars_df.mean(), inplace=True)
print(cars_df.fillna)

print("Q2: Check what are the different types of Make are there in our dataset. And, what is the count (occurrence) of each Make in the data? \n")
make_counts = cars_df['Make'].value_counts()
print("Different types of Make and their occurrence count:")
print(make_counts)

print("Q3: Show all the records where Origin is Asia or Europe. \n")
asia_europe_cars = cars_df[cars_df['Origin'].isin(['Asia', 'Europe'])]
print(asia_europe_cars)

print("Q4: Remove all the records (rows) where Weight is above 4000.\n")
cars_df = cars_df[cars_df['Weight'] <= 4000]
print(cars_df)

print("Q5: Increase all the values of 'MPG_City' column by 3.\n")
cars_df['MPG_City'] += 3
print(cars_df)

print("Display the modified dataframe ")
print("Modified DataFrame:")
print(cars_df)